### ISSUE TITLE
This module can only be run on a Raspberry Pi!

### ISSUE THREAD

**Issue by fred2nice** [BPI-SINOVOIP/RPi.GPIO#10]
Hi there,

I have a BPI M5, debian version :
Linux bananapi 4.9.241-BPI-M5 #2 SMP PREEMPT Mon Jun 21 16:29:40 HKT 2021 aarch64 GNU/Linux

When I tried to use it I still obtain "can only be run on a Raspberry Pi!"

I did
apt-get update
apt-get upgrade
apt-get install python-dev python3-dev
python3 setup.py install
git clone https://github.com/BPI-SINOVOIP/RPi.GPIO
cd RPi.GPIO/
python3 setup.py install
python setup.py install

```
python RPi.GPIO/test/g40.py
BPI: gpioLayout(-1)
Traceback (most recent call last):
  File "RPi.GPIO/test/g40.py", line 2, in <module>
    import RPi.GPIO as GPIO
  File "/usr/local/lib/python2.7/dist-packages/RPi/GPIO/__init__.py", line 23, in <module>
    from RPi._GPIO import *
RuntimeError: This module can only be run on a Raspberry Pi!

```

I tried to upgrade RPI.GPIO from (pip/pip3) 0.6.5 to 0.7, but same issue

Any idea ?
Kind Regards

**Comment by SatsCzar** [comment]
The same error here

**Comment by SatsCzar** [comment]
Hey, take a look:
https://github.com/BPI-SINOVOIP/RPi.GPIO/blob/5c7da1a184ec00eef05f580cddf183436814011b/source/c_gpio_bpi.c#L549

I think that the problem is the file board.sh
After I created the board.sh with 
```
BOARD=bpi-m2z
BOARD_AUTO=bpi-m2z
BOARD_OLD=bpi-m64
```
The code worked
```
pi@bananapim2zero:~/RPi.GPIO$ python3 test/info.py
BPI: gpioLayout(33)
BPI: name[bpi-m2z] gpioLayout(33)
Pi Board Information
---------------------
P1_REVISION => 3
REVISION => 4001
TYPE => Banana Pi M2 Zero[H2+/H3]
MANUFACTURER => BPI-Sinovoip
PROCESSOR => Allwinner
RAM => 512MB
```

**Comment by NeonLightning** [comment]
still didn't work for me. what os version are you using as a base?
